language: r
dist: xenial
cache: packages

os: 
  - osx
  - linux
  
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libgsl-dev
    - libudunits2-dev
    - libgdal-dev
    - libproj-dev

#r_binary_packages:
#  - gsl

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmagick++-dev; fi
  # GSL
  - if [[ "$TRAVIS_OS_NAME" == "mac" ]]; then sudo brew install gsl; fi

after_success:
  - Rscript -e 'lintr::lint_package()'
#  - Rscript -e 'library(covr); codecov()'
#  - Rscript -e 'library(goodpractice); gp()'

