language: r
cache: packages

os: 
  - osx
  - linux

apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libgsl0-dev
      - libcurl4-openssl-dev



r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmagick++-dev; fi

after_success:
  - Rscript -e 'lintr::lint_package()'
#  - Rscript -e 'library(covr); codecov()'
#  - Rscript -e 'library(goodpractice); gp()'

