language: r
cache: packages

os: 
  - osx
  - linux
  
addons:
  apt:
    packages:
    - gsl-bin
    - libgsl0-dev
  
r_binary_packages:
  - gsl

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice

before_install:
  - sudo apt-get update;
  - sudo apt-get install -y libgsl-dev;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmagick++-dev; fi

after_success:
  - Rscript -e 'lintr::lint_package()'
#  - Rscript -e 'library(covr); codecov()'
#  - Rscript -e 'library(goodpractice); gp()'

